[package]
name = "commit-templates"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.6", features = ["derive"] }
colorize = "0.1.0"
regex = "1.5.6"
serde = { version = "1.0.137", features = ["derive"] }
temp-file = "0.1.7"
toml = "0.5.9"
