[feat]
label = "Feat 🎸"
description = "A new feature"
title = "feat: 🎸 {{title}}"
branch_pattern = "^feature/GP-{{nn}}$"
body = """
## Breaking changes

Closes [GP-{{nn}}](https://connectnodes.atlassian.net/browse/GP-{{nn}})
"""
